language: python

python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4

matrix:
  allow_failures:
    - python: 2.7

install:
  - "pip install -r requirements.txt"
  
script:
  - "pep8 --version"
  - "pep8 --max-line-length=119 ."
  - "cp config.example.json config.json"
  - "python travis/test_config.py"
  
notifications:
  email: true
  irc: "irc.esper.net#zarthus"