language: python

python:
  - 3.2
  - 3.3
  - 3.4

install:
  - "pip install -r travis/requirements.txt"

before_script:
  - "pep8 --version"

script:
  - "pep8 --max-line-length=119 ."
  - "cp config.example.json config.json"
  - "python travis/test_config.py"

notifications:
  email: true
  irc:
    channels:
      - "irc.esper.net#zarthus"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit}) %{author}: %{message} -- %{build_url}"